FROM ubuntu:22.04

LABEL maintainer="Jean-Baptiste Auvinet - https://github.com/jbauvinet"

VOLUME ["/opt/rapid7/nexpose/nsc/logs/"]

WORKDIR /opt/rapid7/nexpose/

ENTRYPOINT ["/opt/rapid7/nexpose"]
CMD ["run"]